import React, { useState, useEffect, useMemo } from "react";
import { useNavigate } from "react-router-dom";
import { db } from "../config/firebase";
import { collection, onSnapshot, addDoc, updateDoc, doc, deleteDoc } from "firebase/firestore";
import { useAuth } from "../context/AuthContext";

// Interfaces
interface MapelItem {
  id: string;
  namaMapel: string;
  kodeMapel: string;
  madrasahId: string;
}

interface MapelWithGuru extends MapelItem {
  pengampu: string[];
  isAutoGenerated?: boolean;
}

export default function MapelPage() {
  const navigate = useNavigate();
  const { user, isAdmin, isSuperAdmin, isKepala } = useAuth();
  const canManage = isAdmin || isSuperAdmin || isKepala;

  // Data State
  const [rawGuru, setRawGuru] = useState<any[]>([]);
  const [rawMapel, setRawMapel] = useState<MapelItem[]>([]);
  const [mapelList, setMapelList] = useState<MapelWithGuru[]>([]);
  const [totalGuru, setTotalGuru] = useState<number>(0);
  const [loading, setLoading] = useState<boolean>(true);
  const [search, setSearch] = useState<string>("");

  // State Form Modal / Edit
  const [showForm, setShowForm] = useState<boolean>(false);
  const [isEditing, setIsEditing] = useState<boolean>(false);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [namaMapel, setNamaMapel] = useState<string>("");
  const [kodeMapel, setKodeMapel] = useState<string>("");
  const [saving, setSaving] = useState(false);

  // Alert/Toast State
  const [alertMessage, setAlertMessage] = useState<{ type: "success" | "error" | "info"; text: string } | null>(null);

  const showAlert = (text: string, type: "success" | "error" | "info" = "success") => {
    setAlertMessage({ type, text });
    setTimeout(() => setAlertMessage(null), 4000);
  };

  // 1. SINKRONISASI REAL-TIME DENGAN FIREBASE (onSnapshot)
  useEffect(() => {
    if (!user) {
      navigate("/login");
      return;
    }

    const currentMadrasahId = user.madrasahId || "";
    setLoading(true);

    // Subscribe Real-time ke Koleksi "guru"
    const unsubGuru = onSnapshot(
      collection(db, "guru"),
      (snap) => {
        const gurus = snap.docs
          .map((d) => ({ id: d.id, ...d.data() }))
          .filter((g: any) => !currentMadrasahId || !g.madrasahId || g.madrasahId === currentMadrasahId);
        
        setRawGuru(gurus);
        setTotalGuru(gurus.length);
      },
      (err) => {
        console.error("Gagal mendengar update data guru:", err);
      }
    );

    // Subscribe Real-time ke Koleksi "mapel"
    const unsubMapel = onSnapshot(
      collection(db, "mapel"),
      (snap) => {
        const mapels: MapelItem[] = snap.docs
          .map((d) => {
            const data = d.data();
            // Fleksibel menangani variasi nama field di Firestore
            const nama = data.namaMapel || data.nama || data.mapel || "";
            const kode = data.kodeMapel || data.kode || "";
            return {
              id: d.id,
              ...data,
              namaMapel: nama,
              kodeMapel: kode,
              madrasahId: data.madrasahId || currentMadrasahId,
            } as MapelItem;
          })
          .filter((m) => m.namaMapel.trim() !== "") // Hindari data kosong
          .filter((m) => !currentMadrasahId || !m.madrasahId || m.madrasahId === currentMadrasahId);

        setRawMapel(mapels);
        setLoading(false);
      },
      (err) => {
        console.error("Gagal mendengar update data mapel:", err);
        setLoading(false);
      }
    );

    return () => {
      unsubGuru();
      unsubMapel();
    };
  }, [user, navigate]);

  // 2. OLAHKAN DAN GABUNGKAN DATA (DARI MAPEL TERSIMPAN + PROFIL GURU)
  useEffect(() => {
    const currentMadrasahId = user?.madrasahId || "";

    // Ekstrak nama mapel otomatis dari data Guru
    const extractedMapelNames = new Set<string>();

    rawGuru.forEach((g: any) => {
      const dataMapelGuru = g.mapel || g.mataPelajaran || g.mapelAjar;
      if (dataMapelGuru) {
        if (Array.isArray(dataMapelGuru)) {
          dataMapelGuru.forEach((m: any) => {
            if (typeof m === "string" && m.trim()) {
              extractedMapelNames.add(m.trim());
            }
          });
        } else if (typeof dataMapelGuru === "string") {
          const splitMapel = dataMapelGuru
            .split(",")
            .map((m: string) => m.trim())
            .filter(Boolean);
          splitMapel.forEach((m: string) => extractedMapelNames.add(m));
        }
      }
    });

    // Gabungkan Data Mapel (Prioritas data tersimpan di DB)
    const combinedDataMap = new Map<string, MapelItem & { isAutoGenerated?: boolean }>();

    // Masukkan data dari koleksi mapel terlebih dahulu
    rawMapel.forEach((m) => {
      if (m.namaMapel) {
        combinedDataMap.set(m.namaMapel.toLowerCase(), { ...m, isAutoGenerated: false });
      }
    });

    // Masukkan mapel dari profil Guru jika belum ada di koleksi mapel
    extractedMapelNames.forEach((nama) => {
      const key = nama.toLowerCase();
      if (!combinedDataMap.has(key)) {
        combinedDataMap.set(key, {
          id: `auto_${key}`,
          namaMapel: nama,
          kodeMapel: "",
          madrasahId: currentMadrasahId,
          isAutoGenerated: true,
        });
      }
    });

    // Hubungkan dengan Guru Pengampu masing-masing
    const finalData: MapelWithGuru[] = Array.from(combinedDataMap.values()).map((mapel) => {
      const target = (mapel.namaMapel || "").toLowerCase();
      const pengampu = rawGuru
        .filter((g: any) => {
          const dataMapelGuru = g.mapel || g.mataPelajaran || g.mapelAjar;
          if (!dataMapelGuru || !target) return false;

          if (Array.isArray(dataMapelGuru)) {
            return dataMapelGuru.some(
              (m: any) => typeof m === "string" && m.toLowerCase().includes(target)
            );
          } else if (typeof dataMapelGuru === "string") {
            return dataMapelGuru.toLowerCase().includes(target);
          }
          return false;
        })
        .map((g: any) => g.nama || g.namaGuru || "Guru Anonim");

      return { ...mapel, pengampu };
    });

    // Urutkan berdasarkan Abjad
    finalData.sort((a, b) => (a.namaMapel || "").localeCompare(b.namaMapel || ""));
    setMapelList(finalData);
  }, [rawGuru, rawMapel, user?.madrasahId]);

  const resetForm = () => {
    setNamaMapel("");
    setKodeMapel("");
    setIsEditing(false);
    setSelectedId(null);
    setShowForm(false);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!namaMapel.trim()) {
      showAlert("Nama Mata Pelajaran wajib diisi!", "error");
      return;
    }
    if (!user?.madrasahId) {
      showAlert("ID Madrasah tidak ditemukan.", "error");
      return;
    }

    setSaving(true);
    try {
      const payload = {
        namaMapel: namaMapel.trim(),
        kodeMapel: kodeMapel.trim().toUpperCase(),
        madrasahId: user.madrasahId,
        updatedAt: new Date().toISOString(),
      };

      if (isEditing && selectedId && !selectedId.startsWith("auto_")) {
        await updateDoc(doc(db, "mapel", selectedId), payload);
        showAlert("Berhasil memperbarui mata pelajaran!");
      } else {
        await addDoc(collection(db, "mapel"), {
          ...payload,
          createdAt: new Date().toISOString(),
        });
        showAlert("Berhasil menyimpan mata pelajaran!");
      }

      resetForm();
    } catch (err) {
      console.error(err);
      showAlert("Gagal menyimpan data mata pelajaran.", "error");
    } finally {
      setSaving(false);
    }
  };

  const handleEdit = (item: MapelWithGuru) => {
    setIsEditing(true);
    setSelectedId(item.id);
    setNamaMapel(item.namaMapel);
    setKodeMapel(item.kodeMapel || "");
    setShowForm(true);
  };

  const handleDelete = async (id: string, nama: string) => {
    if (id.startsWith("auto_")) {
      showAlert(
        `"${nama}" adalah mapel otomatis dari profil guru. Hapus mapel ini pada profil Guru pengampu untuk menghilangkannya.`,
        "info"
      );
      return;
    }

    if (window.confirm(`Apakah Anda yakin ingin menghapus data tersimpan mata pelajaran "${nama}"?`)) {
      try {
        await deleteDoc(doc(db, "mapel", id));
        showAlert(`Mata pelajaran "${nama}" berhasil dihapus dari database.`, "info");
      } catch (err) {
        console.error(err);
        showAlert("Gagal menghapus mata pelajaran.", "error");
      }
    }
  };

  const filteredMapel = useMemo(() => {
    const safeSearch = search.toLowerCase();
    return mapelList.filter((item) => {
      const nama = (item.namaMapel || "").toLowerCase();
      const kode = (item.kodeMapel || "").toLowerCase();
      return nama.includes(safeSearch) || kode.includes(safeSearch);
    });
  }, [mapelList, search]);

  const totalPengampu = mapelList.reduce((acc, m) => acc + (m.pengampu?.length || 0), 0);
  const avgPengampu = mapelList.length > 0 ? (totalPengampu / mapelList.length).toFixed(1) : "0.0";

  return (
    <div className="min-h-screen bg-slate-100 flex flex-col font-sans">
      {/* HEADER */}
      <header className="bg-teal-700 text-white p-4 shadow-md flex justify-between items-center">
        <div className="flex items-center space-x-3">
          <button
            onClick={() => navigate("/dashboard")}
            className="bg-teal-800 hover:bg-teal-900 text-white px-3 py-1.5 rounded-lg text-sm transition flex items-center space-x-1"
          >
            <span>←</span>
            <span>Dashboard</span>
          </button>
          <div>
            <h1 className="text-xl font-bold">Modul Mata Pelajaran</h1>
            <p className="text-xs text-teal-100">
              {user?.namaMadrasah || "Madrasah"} | Pengelola: {user?.nama || "Admin"}
            </p>
          </div>
        </div>
        <div className="text-right text-xs bg-teal-800 px-3 py-1.5 rounded-lg border border-teal-600">
          <span className="font-semibold block">{user?.role?.toUpperCase()}</span>
          <span className="opacity-80">Hak Akses Manajemen</span>
        </div>
      </header>

      {/* ALERT / TOAST */}
      {alertMessage && (
        <div className="max-w-7xl mx-auto w-full px-4 md:px-8 pt-4">
          <div
            className={`p-4 rounded-lg shadow-sm border flex justify-between items-center text-sm font-medium ${
              alertMessage.type === "success"
                ? "bg-emerald-50 text-emerald-800 border-emerald-200"
                : alertMessage.type === "error"
                ? "bg-rose-50 text-rose-800 border-rose-200"
                : "bg-sky-50 text-sky-800 border-sky-200"
            }`}
          >
            <div className="flex items-center space-x-2">
              <span>{alertMessage.type === "success" ? "✅" : alertMessage.type === "error" ? "⚠️" : "ℹ️"}</span>
              <span>{alertMessage.text}</span>
            </div>
            <button onClick={() => setAlertMessage(null)} className="text-xs font-bold opacity-60 hover:opacity-100">
              ✕
            </button>
          </div>
        </div>
      )}

      {/* MAIN CONTENT */}
      <div className="p-4 md:p-8 max-w-7xl mx-auto w-full space-y-6">
        {/* STATS CARDS */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-white border border-emerald-200 border-l-4 border-l-emerald-500 p-5 rounded-xl shadow-sm">
            <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Total Mata Pelajaran</p>
            <p className="text-3xl font-extrabold text-emerald-700 mt-1">{mapelList.length}</p>
          </div>
          <div className="bg-white border border-sky-200 border-l-4 border-l-sky-500 p-5 rounded-xl shadow-sm">
            <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Total Guru Terdaftar</p>
            <p className="text-3xl font-extrabold text-sky-700 mt-1">{totalGuru}</p>
          </div>
          <div className="bg-white border border-amber-200 border-l-4 border-l-amber-500 p-5 rounded-xl shadow-sm">
            <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Rata-rata Pengampu / Mapel</p>
            <p className="text-3xl font-extrabold text-amber-600 mt-1">{avgPengampu}</p>
          </div>
        </div>

        {/* ACTION HEADER & SEARCH */}
        <div className="bg-white p-5 rounded-xl shadow-sm border border-slate-200 flex flex-col md:flex-row justify-between items-center gap-4">
          <div>
            <h2 className="text-lg font-bold text-slate-800">📚 Daftar Mata Pelajaran</h2>
            <p className="text-xs text-slate-500 mt-0.5">
              *Data tersinkronisasi secara real-time dari database & profil Guru.
            </p>
          </div>
          <div className="flex flex-col sm:flex-row items-center gap-3 w-full md:w-auto">
            <input
              type="text"
              placeholder="Cari mata pelajaran..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="bg-slate-50 border border-slate-300 rounded-lg px-4 py-2 text-sm outline-none focus:ring-2 focus:ring-teal-500 w-full sm:w-64 transition"
            />
            {canManage && (
              <button
                onClick={() => {
                  resetForm();
                  setShowForm(!showForm);
                }}
                className={`${
                  showForm ? "bg-slate-100 text-slate-700 border border-slate-300" : "bg-teal-600 text-white hover:bg-teal-700"
                } px-4 py-2 rounded-lg text-sm font-semibold whitespace-nowrap transition w-full sm:w-auto`}
              >
                {showForm ? "✕ Tutup Form" : "➕ Tambah Mapel Manual"}
              </button>
            )}
          </div>
        </div>

        {/* FORM MODAL / EDIT */}
        {showForm && canManage && (
          <div className="bg-white p-6 rounded-xl shadow-sm border border-teal-200 animate-fade-in">
            <h3 className="text-md font-bold text-slate-800 mb-4 border-b border-slate-100 pb-2">
              {isEditing ? "✏️ Edit / Tambah Kode Mata Pelajaran" : "➕ Tambah Mata Pelajaran Baru"}
            </h3>
            <form onSubmit={handleSubmit} className="grid grid-cols-1 md:grid-cols-3 gap-5 items-end">
              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">
                  Nama Mata Pelajaran <span className="text-rose-500">*</span>
                </label>
                <input
                  type="text"
                  placeholder="Contoh: Akidah Akhlak"
                  value={namaMapel}
                  onChange={(e) => setNamaMapel(e.target.value)}
                  required
                  className="w-full bg-slate-50 border border-slate-300 rounded-lg px-3 py-2.5 text-sm focus:ring-2 focus:ring-teal-500 outline-none transition"
                />
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">Kode Mapel (Opsional)</label>
                <input
                  type="text"
                  placeholder="Contoh: AKI"
                  value={kodeMapel}
                  onChange={(e) => setKodeMapel(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 rounded-lg px-3 py-2.5 text-sm focus:ring-2 focus:ring-teal-500 outline-none transition uppercase"
                />
              </div>
              <div className="flex gap-2">
                <button
                  type="submit"
                  disabled={saving}
                  className="flex-1 bg-teal-600 hover:bg-teal-700 text-white px-4 py-2.5 rounded-lg text-sm font-bold transition disabled:bg-slate-400"
                >
                  {saving ? "Menyimpan..." : isEditing ? "Simpan Perubahan" : "Simpan Mapel"}
                </button>
                <button
                  type="button"
                  onClick={resetForm}
                  className="bg-slate-100 hover:bg-slate-200 text-slate-700 px-4 py-2.5 rounded-lg text-sm font-bold border border-slate-300 transition"
                >
                  Batal
                </button>
              </div>
            </form>
          </div>
        )}

        {/* GRID KARTU MAPEL */}
        {loading ? (
          <div className="flex flex-col items-center justify-center py-12 bg-white rounded-xl border border-slate-200 shadow-sm space-y-3">
            <div className="w-8 h-8 border-4 border-teal-500 border-t-transparent rounded-full animate-spin"></div>
            <p className="text-slate-500 text-sm">Menyingkronkan data mata pelajaran dari Firebase...</p>
          </div>
        ) : filteredMapel.length === 0 ? (
          <div className="bg-slate-50 py-12 text-center rounded-xl border border-dashed border-slate-300 text-slate-500">
            <div className="text-3xl mb-2">📚</div>
            <p className="text-sm font-medium">Belum ada data mata pelajaran yang ditemukan.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredMapel.map((item) => {
              const kodeDisplay =
                item.kodeMapel || (item.namaMapel ? item.namaMapel.substring(0, 3).toUpperCase() : "MAP");

              return (
                <div
                  key={item.id}
                  className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm hover:shadow-md transition flex flex-col justify-between relative overflow-hidden"
                >
                  {item.isAutoGenerated && (
                    <div className="absolute top-0 right-0 bg-amber-100 text-amber-800 text-[9px] font-bold px-2 py-1 rounded-bl-lg">
                      Terdeteksi Otomatis
                    </div>
                  )}

                  <div className={`${item.isAutoGenerated ? "mt-2" : ""}`}>
                    <div className="flex justify-between items-start mb-3">
                      <h3 className="text-lg font-bold text-slate-800 pr-2">{item.namaMapel || "Mata Pelajaran"}</h3>
                      <span className="text-[10px] font-mono bg-teal-50 text-teal-700 border border-teal-200 px-2 py-1 rounded font-bold tracking-wider">
                        {kodeDisplay}
                      </span>
                    </div>

                    <p className="text-xs text-slate-500 mb-2.5 font-bold">Guru Pengampu ({item.pengampu.length}):</p>

                    {item.pengampu.length > 0 ? (
                      <div className="flex flex-wrap gap-1.5">
                        {item.pengampu.map((namaGuru, idx) => (
                          <span
                            key={idx}
                            className="inline-flex items-center gap-1 text-[11px] bg-slate-100 text-slate-700 border border-slate-200 px-2 py-0.5 rounded-full font-medium"
                          >
                            <span className="text-slate-400">👤</span>
                            {namaGuru}
                          </span>
                        ))}
                      </div>
                    ) : (
                      <p className="text-xs text-rose-500 bg-rose-50 px-2 py-1 rounded inline-block font-medium border border-rose-100">
                        Belum ada pengampu
                      </p>
                    )}
                  </div>

                  {canManage && (
                    <div className="border-t border-slate-100 mt-5 pt-3 flex justify-end gap-2 text-xs">
                      <button
                        onClick={() => handleEdit(item)}
                        className="text-sky-600 hover:text-sky-800 font-semibold bg-sky-50 px-3 py-1.5 rounded border border-sky-100 transition"
                      >
                        Edit
                      </button>
                      <button
                        onClick={() => handleDelete(item.id, item.namaMapel)}
                        className="text-rose-600 hover:text-rose-800 font-semibold bg-rose-50 px-3 py-1.5 rounded border border-rose-100 transition"
                      >
                        Hapus
                      </button>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}